/**
 * Curriculum catalog. Mirrors docs/curriculum/README.md (lesson order, titles,
 * prerequisites). Lesson content lives in per-lesson files registered in
 * registry.js; entries without content are listed as planned.
 *
 * Lessons are listed in teaching order. A lesson's `unit` is its unit's `id`;
 * `number` is the label students see. Unit 3B shares the B prefix with Unit 3,
 * its teaching order is not its ID order, and its last two lessons (B17, B18)
 * are taught after Unit 6, in a second group with the same label.
 */
export const UNITS = [
  { id: 0, number: 0, title: 'Math foundations' },
  { id: 1, number: 1, title: 'Orientation of lines and planes' },
  { id: 2, number: 2, title: 'Stress' },
  { id: 3, number: 3, title: 'Brittle deformation' },
  { id: '3B', number: '3B', title: 'Faults' },
  { id: 4, number: 4, title: 'Deformation and strain' },
  { id: 5, number: 5, title: 'Rheology' },
  { id: 6, number: 6, title: 'Folds and folding' },
  { id: '3B-after-6', number: '3B', title: 'Faults, continued (taught after Unit 6)' },
];

export const LESSON_CATALOG = [
  { id: 'M1', unit: 0, title: 'Vectors and components', prerequisites: [] },
  { id: 'M2', unit: 0, title: 'Trigonometry of projection', prerequisites: ['M1'] },
  { id: 'M3', unit: 0, title: 'Dot and cross products', prerequisites: ['M1', 'M2'] },
  { id: 'M4', unit: 0, title: 'Matrices as transformations', prerequisites: ['M1', 'M3'] },
  { id: 'O1', unit: 1, title: 'The geographic frame and lines', prerequisites: ['M1', 'M2', 'M4'] },
  { id: 'O2', unit: 1, title: 'Planes: strike, dip, and poles', prerequisites: ['O1', 'M3'] },
  { id: 'O3', unit: 1, title: 'Stereonets', prerequisites: ['O1', 'O2'] },
  { id: 'O4', unit: 1, title: 'Angles, intersections, and rake', prerequisites: ['O3', 'M3'] },
  { id: 'S1', unit: 2, title: 'Force', prerequisites: ['M1'] },
  { id: 'S2', unit: 2, title: 'Force vs traction', prerequisites: ['S1', 'M2'] },
  { id: 'S3', unit: 2, title: 'Normal and shear traction on any plane', prerequisites: ['S2', 'M3'] },
  { id: 'S4', unit: 2, title: 'Stress at a point (2D)', prerequisites: ['S3', 'M4'] },
  { id: 'S5', unit: 2, title: 'Transformation and principal stresses (2D)', prerequisites: ['S4', 'M2', 'M4'] },
  { id: 'S6', unit: 2, title: 'The Mohr circle (2D)', prerequisites: ['S5'] },
  { id: 'S7', unit: 2, title: 'The stress tensor in 3D', prerequisites: ['S4', 'S6', 'O2', 'M4'] },
  { id: 'S8', unit: 2, title: 'Principal stresses in 3D', prerequisites: ['S7', 'M4', 'O3'] },
  { id: 'S9', unit: 2, title: 'The 3D Mohr diagram', prerequisites: ['S6', 'S8'] },
  { id: 'S10', unit: 2, title: 'Mean, deviatoric, and Earth stress states', prerequisites: ['S8', 'S9', 'O1'] },
  { id: 'B1', unit: 3, title: 'Brittle processes, fracture modes, and deformation bands', prerequisites: ['S8', 'S10'] },
  { id: 'B2', unit: 3, title: 'Tensile failure', prerequisites: ['B1', 'S6', 'S10'] },
  { id: 'B3', unit: 3, title: 'Coulomb failure and the composite failure envelope', prerequisites: ['B2', 'S9', 'O4'] },
  { id: 'B4', unit: 3, title: 'Confining pressure and pore-fluid pressure', prerequisites: ['B3', 'S10'] },
  { id: 'B5', unit: 3, title: 'Joints and veins', prerequisites: ['B2', 'B4', 'O3'] },
  { id: 'B6', unit: 3, title: 'Friction and reactivation of existing planes', prerequisites: ['B3', 'B4', 'S9', 'O3'] },
  { id: 'B7', unit: '3B', title: "Anderson's theory of faulting", prerequisites: ['B3', 'B6', 'S10', 'O2'] },
  { id: 'B8', unit: '3B', title: 'Fault geometry, slip, and kinematic axes', prerequisites: ['B7', 'O4', 'S7'] },
  { id: 'B10', unit: '3B', title: 'Fault shapes, arrays, and terminations', prerequisites: ['B8', 'O2', 'M2'] },
  { id: 'B11', unit: '3B', title: 'Fault zones and fault rocks', prerequisites: ['B8', 'B10', 'B6', 'B1'] },
  { id: 'B12', unit: '3B', title: 'Kinematic indicators', prerequisites: ['B8', 'B11', 'B3', 'O3'] },
  { id: 'B9', unit: '3B', title: 'Fault displacement and growth', prerequisites: ['B8', 'B6', 'B11'] },
  { id: 'B13', unit: '3B', title: 'Faults and earthquakes', prerequisites: ['B6', 'B9', 'B11', 'S7'] },
  { id: 'B14', unit: '3B', title: 'Fault mechanics puzzles', prerequisites: ['B4', 'B6', 'B7', 'B10', 'B13'] },
  { id: 'B15', unit: '3B', title: 'Fault populations and paleostress', prerequisites: ['B8', 'B9', 'B12', 'S8', 'O3'] },
  { id: 'B16', unit: '3B', title: 'Faults, fluids, and the subsurface', prerequisites: ['B8', 'B9', 'B10', 'B11'] },
  { id: 'D1', unit: 4, title: 'Components of deformation', prerequisites: ['M4', 'S10'] },
  { id: 'D2', unit: 4, title: 'Homogeneous vs heterogeneous deformation', prerequisites: ['D1'] },
  { id: 'D3', unit: 4, title: 'Measuring strain', prerequisites: ['D2'] },
  { id: 'D4', unit: 4, title: 'The strain ellipse and ellipsoid', prerequisites: ['D3', 'M4', 'S8'] },
  { id: 'D5', unit: 4, title: 'Coaxial and non-coaxial deformation: pure shear, uniaxial strain, and simple shear', prerequisites: ['D4', 'M2'] },
  { id: 'D6', unit: 4, title: 'Flow: velocity fields, ISA, flow apophyses, and vorticity', prerequisites: ['D5', 'M4'] },
  { id: 'D7', unit: 4, title: 'Progressive deformation', prerequisites: ['D6'] },
  { id: 'D8', unit: 4, title: 'Strain measurement methods', prerequisites: ['D4', 'D3'] },
  { id: 'R1', unit: 5, title: 'What rheology is', prerequisites: ['S10', 'D4'] },
  { id: 'R2', unit: 5, title: 'Elasticity', prerequisites: ['R1', 'S7', 'D4'] },
  { id: 'R3', unit: 5, title: 'Viscous flow', prerequisites: ['R1', 'D5'] },
  { id: 'R4', unit: 5, title: 'Plastic and composite behavior', prerequisites: ['R2', 'R3'] },
  { id: 'R5', unit: 5, title: 'Stress in the crust: reference states and tectonic stress', prerequisites: ['R2', 'R4', 'S10', 'B4', 'B7', 'D5'] },
  { id: 'R6', unit: 5, title: 'Controls and the brittle–ductile transition', prerequisites: ['R4', 'R5', 'B6', 'B7', 'S10'] },
  { id: 'F1', unit: 6, title: 'Fold anatomy', prerequisites: ['O2', 'O3'] },
  { id: 'F2', unit: 6, title: 'Fold orientation and stereonets', prerequisites: ['F1', 'O3', 'O4'] },
  { id: 'F3', unit: 6, title: 'Fold shape and classification', prerequisites: ['F2'] },
  { id: 'F4', unit: 6, title: 'Folding mechanisms', prerequisites: ['F3', 'D4', 'D5', 'D6', 'D7', 'R3', 'R4'] },
  { id: 'F5', unit: 6, title: 'Boudinage', prerequisites: ['F4', 'D4', 'D7', 'R4', 'B5'] },
  { id: 'F6', unit: 6, title: 'Fault-related folds', prerequisites: ['F4', 'B8', 'B9', 'B10', 'D6', 'O4'] },
  { id: 'F7', unit: 6, title: 'Superposed folding', prerequisites: ['F4', 'F2', 'D7'] },
  { id: 'B17', unit: '3B-after-6', title: 'Extensional and contractional fault systems, and inversion', prerequisites: ['B9', 'B10', 'B14', 'B15', 'F6'] },
  { id: 'B18', unit: '3B-after-6', title: 'Strike-slip fault systems', prerequisites: ['B10', 'B12', 'B15', 'B17', 'D5', 'D6', 'F6'] },
];
