export const STRESS_LESSON = {
  id: 'reading-stress-states',
  title: 'Reading stress states',
  duration: '15–20 minutes',
  summary: 'Connect vector direction and magnitude to visible shape and volume change.',
  steps: [
    {
      id: 'orient-the-block',
      label: 'Orient the block',
      title: 'Start with the reference shape',
      activeLabel: 'Undeformed reference block',
      body: 'Use the colored x, y, and z axes to orient the block. The dashed outline records its original dimensions so every later change has a visual reference.',
      presetId: 'uniaxial-tension',
      magnitude: 0,
      vectors: false,
      outline: true,
      grid: true,
      spotlight: 'axes',
      responseOverride: 'The solid block and dashed outline coincide before stress is applied.',
    },
    {
      id: 'read-the-vectors',
      label: 'Read the vectors',
      title: 'Direction and magnitude come first',
      body: 'The teal arrows point away from opposite faces. Their orientation identifies the loaded axis, while their length and the MPa readout communicate magnitude.',
      presetId: 'uniaxial-tension',
      magnitude: 22,
      vectors: true,
      outline: true,
      grid: true,
      spotlight: 'vectors',
      responseOverride: 'Outward vectors indicate tension along the x-axis.',
    },
    {
      id: 'predict-tension',
      label: 'Predict tension',
      title: 'Predict before the block responds',
      body: 'This is uniaxial tension: one negative normal-stress component in the compression-positive convention.',
      presetId: 'uniaxial-tension',
      magnitude: 28,
      vectors: true,
      outline: true,
      grid: true,
      spotlight: 'response',
      prompt: 'What change should be most visible along the x-axis?',
      choices: [
        { id: 'shorten', label: 'It shortens', correct: false, feedback: 'That is the expected response to compression along x.' },
        { id: 'extend', label: 'It extends', correct: true, feedback: 'Correct. The block extends parallel to the tensile vectors.' },
        { id: 'unchanged', label: 'It stays unchanged', correct: false, feedback: 'The applied tensile stress produces a visible extension in this qualitative model.' },
      ],
    },
    {
      id: 'reverse-the-loading',
      label: 'Reverse the loading',
      title: 'Reverse the arrows, reverse the response',
      body: 'Orange arrows point toward the block. Compression is positive here, so σx is now positive rather than negative.',
      presetId: 'uniaxial-compression',
      magnitude: 28,
      vectors: true,
      outline: true,
      grid: true,
      spotlight: 'response',
      prompt: 'Compared with the dashed outline, what should happen along x?',
      choices: [
        { id: 'extend', label: 'It extends', correct: false, feedback: 'Extension is associated with tension, not compression along x.' },
        { id: 'shorten', label: 'It shortens', correct: true, feedback: 'Correct. The loaded axis shortens and the lateral directions widen slightly.' },
        { id: 'shear', label: 'It only shears', correct: false, feedback: 'A normal compressive component primarily changes length along its axis.' },
      ],
    },
    {
      id: 'shape-versus-volume',
      label: 'Shape vs. volume',
      title: 'Shape change is not always volume change',
      body: 'Purple arrows identify shear components. Compare the tilted solid block with its original dashed outline and watch the volume readout.',
      presetId: 'pure-shear',
      magnitude: 28,
      vectors: true,
      outline: true,
      grid: true,
      spotlight: 'volume',
      prompt: 'What changes most in this pure-shear example?',
      choices: [
        { id: 'volume', label: 'Its volume', correct: false, feedback: 'The volume readout remains approximately zero in this shear-only model.' },
        { id: 'shape', label: 'Its shape', correct: true, feedback: 'Correct. The block distorts while retaining approximately the same volume.' },
        { id: 'nothing', label: 'Nothing', correct: false, feedback: 'Compare the solid edges with the dashed reference: the shape has changed clearly.' },
      ],
    },
    {
      id: 'combine-components',
      label: 'Combine components',
      title: 'Real stress states can combine effects',
      body: 'This case superimposes simple shear on triaxial compression. Purple and orange vectors appear together, and the block both distorts and contracts.',
      presetId: 'simple-shear-triaxial-compression',
      magnitude: 30,
      vectors: true,
      outline: true,
      grid: true,
      spotlight: 'combined',
      responseOverride: 'Combined components can change both shape and volume at the same time.',
    },
    {
      id: 'explore-all-cases',
      label: 'Explore all cases',
      title: 'Use the full explorer',
      body: 'You now have the vocabulary to compare all ten cases. Open Explore mode to change magnitudes, edit tensor components, and look for recurring patterns.',
      presetId: 'biaxial-tension-compression',
      magnitude: 26,
      vectors: true,
      outline: true,
      grid: true,
      spotlight: 'explore',
      responseOverride: 'Continue into the sandbox and test your own comparisons.',
      final: true,
    },
  ],
};

export function getLessonStep(index) {
  return STRESS_LESSON.steps[Math.min(Math.max(index, 0), STRESS_LESSON.steps.length - 1)];
}

export function isLessonChoiceCorrect(step, choiceId) {
  return step.choices?.find((choice) => choice.id === choiceId)?.correct ?? false;
}
