const centeredTopLoad = {
  surfaceNormal: { x: 0, y: 1, z: 0 },
  applicationPoint: { x: 0, y: 1.25, z: 0 },
};

export const STRESS_LESSON = {
  id: 'loads-to-internal-stress-states',
  title: 'Loads, internal stress, and stress states',
  duration: '55–70 minutes',
  summary: 'Follow a load from external force and moment through equilibrium, internal action, traction, stress, and the stress tensor.',
  steps: [
    {
      id: 'construct-force-vector',
      label: 'Construct a force vector',
      title: 'Build a force vector in three dimensions',
      activeLabel: 'Force vector laboratory',
      activeNumber: 'L1',
      body: 'A force has magnitude and direction. Drag the white handle or enter Fx, Fy, and Fz; the arrow and components remain synchronized.',
      task: 'Set F = (3, −4, 0) kN and determine its magnitude.',
      visualKind: 'force-lab',
      controls: ['magnitude', 'components'],
      labOptions: { showApplicationPoint: true, allowForceDrag: true },
      initialLabState: { ...centeredTopLoad, forceVector: { x: 3_000, y: -4_000, z: 0 }, constraintMode: 'free' },
      presetId: 'uniaxial-compression', magnitude: 0, vectors: false, outline: false, grid: false,
      spotlight: 'force',
      prompt: 'What is the magnitude of F = (3, −4, 0) kN?',
      choices: [
        { id: 'three', label: '3 kN', correct: false, feedback: 'That is only the x-component. Include all components.' },
        { id: 'five', label: '5 kN', correct: true, feedback: 'Correct. √(3² + (−4)² + 0²) = 5 kN.' },
        { id: 'seven', label: '7 kN', correct: false, feedback: 'Vector magnitude is not the sum of component magnitudes.' },
      ],
      responseOverride: 'Components and magnitude are two representations of the same force.',
    },
    {
      id: 'force-location-and-moment',
      label: 'Move the force',
      title: 'Where a force acts changes its rotational effect',
      activeLabel: 'Force and moment',
      activeNumber: 'L2',
      body: 'The orange ring marks the application point. Drag it across the face. The force remains unchanged, but its moment about the block center changes according to M = r × F.',
      task: 'Move the load from the center toward a corner and watch the rotation tendency grow.',
      visualKind: 'force-lab',
      controls: ['components', 'application'],
      labOptions: { showApplicationPoint: true, showResultants: true, showResponse: true, allowApplicationPoint: true, allowSurfaceSelection: true, allowForceDrag: true },
      initialLabState: { ...centeredTopLoad, forceVector: { x: 0, y: -5_000, z: 0 }, constraintMode: 'free' },
      presetId: 'uniaxial-compression', magnitude: 0, vectors: false, outline: false, grid: false,
      spotlight: 'moment',
      prompt: 'For the same force, which application produces the larger moment about the center?',
      choices: [
        { id: 'center', label: 'Through the center', correct: false, feedback: 'A centered normal force has no lever arm about the center.' },
        { id: 'off-center', label: 'Farther from the center', correct: true, feedback: 'Correct. Increasing the perpendicular lever arm increases |r × F|.' },
      ],
      responseOverride: 'Force location controls rotational tendency even when magnitude and direction do not change.',
    },
    {
      id: 'free-body-response',
      label: 'Observe a free body',
      title: 'An unbalanced force does not create static equilibrium',
      activeLabel: 'Free-body motion tendency',
      activeNumber: 'L3',
      body: 'With no support, a nonzero resultant force causes translation and a nonzero resultant moment causes rotation. The blue ghost shows the direction of the rigid-body response; it is not elastic deformation.',
      task: 'Drag the force and its application point. Create translation with little rotation, then create both together.',
      visualKind: 'force-lab',
      controls: ['magnitude', 'components', 'application'],
      labOptions: { showApplicationPoint: true, showResultants: true, showResponse: true, allowApplicationPoint: true, allowSurfaceSelection: true, allowForceDrag: true },
      initialLabState: { ...centeredTopLoad, forceVector: { x: 2_000, y: -4_500, z: 0 }, constraintMode: 'free' },
      presetId: 'uniaxial-compression', magnitude: 0, vectors: false, outline: false, grid: false,
      spotlight: 'free-body',
      prompt: 'Can one nonzero force acting alone keep a free block in static equilibrium?',
      choices: [
        { id: 'yes', label: 'Yes', correct: false, feedback: 'A free block requires zero resultant force and zero resultant moment for static equilibrium.' },
        { id: 'no', label: 'No', correct: true, feedback: 'Correct. Another force, a reaction, or a constraint is required.' },
      ],
      responseOverride: 'Unbalanced force and moment produce rigid-body translation and rotation tendencies.',
    },
    {
      id: 'constraints-and-reactions',
      label: 'Add a support',
      title: 'A constraint supplies reactions and permits internal loading',
      activeLabel: 'Equilibrium and reactions',
      activeNumber: 'L4',
      body: 'Fixing the opposite face supplies the force and moment reactions needed for equilibrium. The green support and reaction vector make that previously hidden assumption visible.',
      task: 'Switch between Free body and Fixed opposite face. Compare the motion tendency with the restrained deformation.',
      visualKind: 'force-lab',
      controls: ['constraint', 'magnitude', 'components'],
      labOptions: { showApplicationPoint: true, showResultants: true, showSupport: true, showReactions: true, showResponse: true, allowApplicationPoint: true, allowSurfaceSelection: true, allowForceDrag: true },
      initialLabState: { ...centeredTopLoad, forceVector: { x: 2_000, y: -5_000, z: 0 }, constraintMode: 'fixed' },
      presetId: 'uniaxial-compression', magnitude: 0, vectors: false, outline: false, grid: false,
      spotlight: 'equilibrium',
      prompt: 'In the fixed case, why is the applied force not the complete free-body diagram?',
      choices: [
        { id: 'reaction', label: 'The support adds reactions', correct: true, feedback: 'Correct. Support reactions balance the applied force and moment.' },
        { id: 'force-disappears', label: 'The applied force disappears', correct: false, feedback: 'The applied force remains; the support supplies balancing reactions.' },
      ],
      responseOverride: 'A restrained body can carry internal action because reactions enforce equilibrium.',
    },
    {
      id: 'create-loading-actions',
      label: 'Create loading modes',
      title: 'Direction and position create different structural actions',
      activeLabel: 'Interactive loading modes',
      activeNumber: 'L5',
      body: 'Normal, tangential, and eccentric forces produce different combinations of axial action, shear, bending, and torsion. These actions emerge from the load geometry rather than from a preset label.',
      task: 'Use the quick directions and move the orange ring. Construct compression, tension, shear with bending, and an eccentric load.',
      visualKind: 'force-lab',
      controls: ['magnitude', 'components', 'presets', 'application'],
      labOptions: { showSurfaceNormal: true, showApplicationPoint: true, showSupport: true, showReactions: true, showResponse: true, allowApplicationPoint: true, allowSurfaceSelection: true, allowForceDrag: true },
      initialLabState: { ...centeredTopLoad, forceVector: { x: 0, y: -5_000, z: 0 }, constraintMode: 'fixed' },
      presetId: 'uniaxial-compression', magnitude: 0, vectors: false, outline: false, grid: false,
      spotlight: 'actions',
      responseOverride: 'Face, angle, magnitude, and application point jointly determine the resulting action.',
    },
    {
      id: 'distribute-force-over-area',
      label: 'Distribute the load',
      title: 'A resultant force can represent a distributed surface load',
      activeLabel: 'Resultant and load distribution',
      activeNumber: 'L6',
      body: 'The white arrow is the resultant. The smaller orange arrows show one idealized uniform distribution that produces it. Changing area changes load intensity without changing the resultant.',
      task: 'Hold force fixed and compare 50 cm² with 100 cm². Notice what changes—and what does not.',
      visualKind: 'force-lab',
      controls: ['magnitude', 'area'],
      labOptions: { showSurfaceNormal: true, showArea: true, showDistribution: true, showSupport: true, showResponse: true, allowSurfaceSelection: true, allowForceDrag: true },
      initialLabState: { ...centeredTopLoad, forceVector: { x: 0, y: -5_000, z: 0 }, constraintMode: 'fixed', contactArea: 100 },
      presetId: 'uniaxial-compression', magnitude: 0, vectors: false, outline: false, grid: false,
      spotlight: 'area',
      prompt: 'If force is fixed while loaded area is halved, what happens to average load intensity?',
      choices: [
        { id: 'halves', label: 'It is halved', correct: false, feedback: 'The same resultant is concentrated over less area.' },
        { id: 'doubles', label: 'It doubles', correct: true, feedback: 'Correct. Force divided by half the area is twice as large.' },
        { id: 'same', label: 'It stays the same', correct: false, feedback: 'Area is in the denominator.' },
      ],
      responseOverride: 'A resultant summarizes a load distribution; area controls its average intensity.',
    },
    {
      id: 'reveal-internal-cut',
      label: 'Make an imaginary cut',
      title: 'An imaginary cut exposes internal action',
      activeLabel: 'Section cut and internal equilibrium',
      activeNumber: 'I1',
      body: 'Cut the restrained block conceptually and isolate one side. The internal force and moment on the cut must balance the external loading on that portion.',
      task: 'Move the cut from the support toward the loaded face. Compare how internal force and internal moment change.',
      visualKind: 'force-lab',
      controls: ['cut', 'application'],
      labOptions: { showApplicationPoint: true, showSupport: true, showResponse: true, showCut: true, showInternalActions: true, allowApplicationPoint: true, allowForceDrag: true },
      initialLabState: { ...centeredTopLoad, forceVector: { x: 2_500, y: -4_500, z: 0 }, constraintMode: 'fixed', cutPosition: -0.3 },
      presetId: 'pure-shear', magnitude: 0, vectors: false, outline: false, grid: false,
      spotlight: 'cut',
      prompt: 'For a single end force, which internal resultant stays constant as the cut moves?',
      choices: [
        { id: 'force', label: 'Internal force', correct: true, feedback: 'Correct. Every cut must balance the same end force; the moment changes with lever arm.' },
        { id: 'moment', label: 'Internal moment', correct: false, feedback: 'The moment changes as the distance from the cut to the applied force changes.' },
      ],
      responseOverride: 'Internal section forces and moments are required by equilibrium; they are not added decorations.',
    },
    {
      id: 'resolve-section-actions',
      label: 'Resolve internal action',
      title: 'Internal force and moment have distinct components',
      activeLabel: 'Axial, shear, bending, and torsion',
      activeNumber: 'I2',
      body: 'Resolve internal force into axial and shear components. Resolve internal moment into bending and torsion. Change the force direction and application point to see each component respond continuously.',
      task: 'Create a case dominated by axial force, then one with bending, and finally one with torsion.',
      visualKind: 'force-lab',
      controls: ['components', 'presets', 'application', 'cut'],
      labOptions: { showSurfaceNormal: true, showApplicationPoint: true, showSupport: true, showResponse: true, showCut: true, showInternalActions: true, allowApplicationPoint: true, allowSurfaceSelection: true, allowForceDrag: true },
      initialLabState: { ...centeredTopLoad, forceVector: { x: 2_500, y: -4_500, z: 0 }, constraintMode: 'fixed', cutPosition: 0 },
      presetId: 'pure-shear', magnitude: 0, vectors: false, outline: false, grid: false,
      spotlight: 'internal-actions',
      responseOverride: 'Axial force, shear force, bending moment, and torsion describe different internal resultants.',
    },
    {
      id: 'calculate-average-traction',
      label: 'Define average traction',
      title: 'Force distributed over area produces traction',
      activeLabel: 'Average traction, t̄ = F/A',
      activeNumber: 'T1',
      body: 'Average traction is a vector with stress units. It describes force intensity on a specified surface; it is not yet the complete stress state at a point.',
      task: 'Set |F| = 5 kN and A = 100 cm². Confirm the conversion to 0.50 MPa.',
      visualKind: 'force-lab',
      controls: ['magnitude', 'area'],
      labOptions: { showSurfaceNormal: true, showArea: true, showDistribution: true, showSupport: true, showResponse: true, allowSurfaceSelection: true, allowForceDrag: true },
      initialLabState: { ...centeredTopLoad, forceVector: { x: 0, y: -5_000, z: 0 }, constraintMode: 'fixed', contactArea: 100 },
      presetId: 'uniaxial-compression', magnitude: 0, vectors: false, outline: false, grid: false,
      spotlight: 'traction',
      prompt: 'What is |t̄| for 5 kN distributed uniformly over 100 cm²?',
      choices: [
        { id: 'point-zero-five', label: '0.05 MPa', correct: false, feedback: 'Check the conversion from square centimeters to square meters.' },
        { id: 'point-five', label: '0.50 MPa', correct: true, feedback: 'Correct. 5,000 N / 0.01 m² = 0.50 MPa.' },
        { id: 'five', label: '5.0 MPa', correct: false, feedback: 'That is one order of magnitude too large.' },
      ],
      responseOverride: 'Traction connects a surface force resultant to force intensity on that surface.',
    },
    {
      id: 'decompose-traction',
      label: 'Resolve normal and shear',
      title: 'Traction has normal and shear components',
      activeLabel: 'Traction decomposition',
      activeNumber: 'T2',
      body: 'Project traction onto the surface normal. The signed projection is normal traction; the remaining in-plane vector is shear traction. Drag the force and watch both change with angle and magnitude.',
      task: 'Choose Oblique and adjust the direction until normal and shear magnitudes are approximately equal.',
      visualKind: 'force-lab',
      controls: ['components', 'area', 'presets'],
      labOptions: { showSurfaceNormal: true, showArea: true, showDecomposition: true, showSupport: true, showResponse: true, allowSurfaceSelection: true, allowForceDrag: true },
      initialLabState: { ...centeredTopLoad, forceVector: { x: 3_535, y: -3_535, z: 0 }, constraintMode: 'fixed', contactArea: 100 },
      presetId: 'pure-shear', magnitude: 0, vectors: false, outline: false, grid: false,
      spotlight: 'decomposition',
      prompt: 'At 45° to the surface normal, how do the normal and shear magnitudes compare?',
      choices: [
        { id: 'normal-larger', label: 'Normal is larger', correct: false, feedback: 'At 45°, the two projections have equal magnitudes.' },
        { id: 'equal', label: 'They are equal', correct: true, feedback: 'Correct. The sine and cosine projections are equal at 45°.' },
        { id: 'shear-zero', label: 'Shear is zero', correct: false, feedback: 'Shear vanishes only for a force exactly normal to the plane.' },
      ],
      responseOverride: 'Normal and shear traction are components of one surface-traction vector.',
    },
    {
      id: 'why-stress-needs-a-tensor',
      label: 'Motivate the tensor',
      title: 'Stress at a point must describe every plane orientation',
      activeLabel: 'From traction to the stress tensor',
      activeNumber: 'T3',
      body: 'One traction vector describes one plane. A complete stress state must predict traction on every plane through the point. The stress tensor is the operator that performs that mapping: t(n) = −σn under this compression-positive convention.',
      task: 'Orbit the cube and identify the one active normal component and the corresponding face tractions.',
      visualKind: 'stress-state',
      presetId: 'uniaxial-compression', magnitude: 20, vectors: true, outline: true, grid: true,
      spotlight: 'tensor',
      responseOverride: 'The tensor compactly describes how traction depends on plane orientation.',
    },
    {
      id: 'compare-normal-stress-states',
      label: 'Build normal states',
      title: 'Normal components combine into different stress states',
      activeLabel: 'Uniaxial tension',
      activeNumber: 'S1',
      body: 'Uniaxial, biaxial, and triaxial states differ by which normal components act together. Compression is positive and tension is negative in the declared geological convention.',
      task: 'Use Back and Continue to compare the constructed loading ideas with this tensor representation.',
      visualKind: 'stress-state',
      presetId: 'uniaxial-tension', magnitude: 28, vectors: true, outline: true, grid: true,
      spotlight: 'response',
      prompt: 'What should be most visible along the loaded x-axis in uniaxial tension?',
      choices: [
        { id: 'shorten', label: 'Shortening', correct: false, feedback: 'Shortening corresponds to compression along x.' },
        { id: 'extend', label: 'Extension', correct: true, feedback: 'Correct. The qualitative response extends parallel to tensile loading.' },
        { id: 'unchanged', label: 'No change', correct: false, feedback: 'The tensile component produces visible extension.' },
      ],
      responseOverride: 'A stress state combines normal and shear components acting at one point.',
    },
    {
      id: 'compare-shear-and-combined-states',
      label: 'Add shear components',
      title: 'Shear and normal components can act simultaneously',
      activeLabel: 'Combined stress state',
      activeNumber: 'S2',
      body: 'Off-diagonal components describe shear traction on coordinate planes. Combined states contain both normal and shear components; their effects cannot be inferred from a single external arrow.',
      task: 'Identify at least one normal component and one shear component in the displayed matrix.',
      visualKind: 'stress-state',
      presetId: 'simple-shear-triaxial-compression', magnitude: 30, vectors: true, outline: true, grid: true,
      spotlight: 'combined',
      prompt: 'Which representation completely specifies the displayed stress state at the point?',
      choices: [
        { id: 'one-arrow', label: 'One force arrow', correct: false, feedback: 'A single arrow describes force or traction on one surface, not the complete state.' },
        { id: 'tensor', label: 'The stress tensor', correct: true, feedback: 'Correct. Its components determine traction on every plane orientation.' },
      ],
      responseOverride: 'Combined states require the full tensor, not a single force or traction vector.',
    },
    {
      id: 'open-stress-explorer',
      label: 'Open the laboratory',
      title: 'Construct and compare complete stress states',
      activeLabel: 'Stress-state laboratory',
      activeNumber: 'S3',
      body: 'Use Explore to compare reference states and edit tensor components. Keep the chain of reasoning visible: external loads, equilibrium, internal resultants, surface traction, and finally stress state.',
      task: 'Choose two states with similar magnitudes and explain why their block responses differ.',
      visualKind: 'stress-state',
      presetId: 'biaxial-tension-compression', magnitude: 26, vectors: true, outline: true, grid: true,
      spotlight: 'explore',
      responseOverride: 'Continue into the open stress-state laboratory and construct your own comparisons.',
      final: true,
    },
  ],
};

export function getLessonStep(index) {
  return STRESS_LESSON.steps[Math.min(Math.max(index, 0), STRESS_LESSON.steps.length - 1)];
}

export function isLessonChoiceCorrect(step, choiceId) {
  return step.choices?.find((choice) => choice.id === choiceId)?.correct ?? false;
}
