export const STRESS_LESSON = {
  id: 'mechanics-foundations-to-stress-states',
  title: 'Forces, traction, and stress states',
  duration: '35–45 minutes',
  summary: 'Construct force vectors on surfaces, resolve traction, and connect those ideas to the stress tensor.',
  steps: [
    {
      id: 'construct-force-vector',
      label: 'Construct a force vector',
      title: 'Build a force vector in three dimensions',
      activeLabel: '3D force laboratory',
      activeNumber: 'F1',
      body: 'A force vector is defined by components, not by an arrow color. Drag the round handle or enter Fx, Fy, and Fz. The arrow and numerical representation remain synchronized.',
      task: 'Set F = (3, −4, 0) kN. Then determine its magnitude.',
      visualKind: 'force-lab',
      controls: ['magnitude', 'components'],
      labOptions: { showSurfaceNormal: false, showArea: false, showDecomposition: false, allowSurfaceSelection: false },
      presetId: 'uniaxial-compression',
      magnitude: 0,
      vectors: false,
      outline: false,
      grid: false,
      spotlight: 'force',
      prompt: 'What is the magnitude of F = (3, −4, 0) kN?',
      choices: [
        { id: 'three', label: '3 kN', correct: false, feedback: 'That is only the x-component. Use the Euclidean magnitude of all components.' },
        { id: 'five', label: '5 kN', correct: true, feedback: 'Correct. √(3² + (−4)² + 0²) = 5 kN.' },
        { id: 'seven', label: '7 kN', correct: false, feedback: 'Vector magnitude is not the sum of the component magnitudes.' },
      ],
      responseOverride: 'Vector components and magnitude describe the same force in different forms.',
    },
    {
      id: 'force-on-a-surface',
      label: 'Relate force to a surface',
      title: 'Direction is measured relative to a surface',
      activeLabel: 'Force and surface orientation',
      activeNumber: 'F2',
      body: 'Click a block face to select its outward unit normal, n. Then drag the force. Normal and tangential are relationships between the force direction and the selected surface—not fixed global directions.',
      task: 'Select two different faces. Use the quick directions to compare normal, oblique, and tangential loading.',
      visualKind: 'force-lab',
      controls: ['components', 'presets'],
      labOptions: { showSurfaceNormal: true, showArea: false, showDecomposition: false, allowSurfaceSelection: true },
      presetId: 'uniaxial-compression',
      magnitude: 0,
      vectors: false,
      outline: false,
      grid: false,
      spotlight: 'surface',
      responseOverride: 'The same global force can be normal, oblique, or tangential to different planes.',
    },
    {
      id: 'area-distributes-force',
      label: 'Change contact area',
      title: 'A resultant force is distributed over an area',
      activeLabel: 'Force distributed over a surface',
      activeNumber: 'F3',
      body: 'The highlighted patch represents the area carrying the resultant force. Keep force fixed and vary the patch. A smaller area produces a larger average traction magnitude.',
      task: 'Compare 50 cm² and 100 cm² without changing the force vector.',
      visualKind: 'force-lab',
      controls: ['area'],
      labOptions: { showSurfaceNormal: true, showArea: true, showDecomposition: false, allowSurfaceSelection: true },
      presetId: 'uniaxial-compression',
      magnitude: 0,
      vectors: false,
      outline: false,
      grid: false,
      spotlight: 'area',
      prompt: 'If the resultant force stays fixed while area is halved, what happens to average traction?',
      choices: [
        { id: 'halves', label: 'It is halved', correct: false, feedback: 'The same force is concentrated over less area, so traction increases.' },
        { id: 'doubles', label: 'It doubles', correct: true, feedback: 'Correct. Dividing by half the area produces twice the average traction.' },
        { id: 'same', label: 'It is unchanged', correct: false, feedback: 'Area appears in the denominator, so it changes the result.' },
      ],
      responseOverride: 'Average traction is inversely proportional to the loaded area when force is fixed.',
    },
    {
      id: 'calculate-average-traction',
      label: 'Calculate traction',
      title: 'Force per area gives average traction',
      activeLabel: 'Average traction, t̄ = F/A',
      activeNumber: 'F4',
      body: 'For a stated uniform distribution, the resultant force divided by contact area gives the average traction vector. This is a vector with stress units, not yet the complete stress tensor at a point.',
      task: 'Set |F| = 5 kN and A = 100 cm². Confirm the unit conversion and resulting magnitude.',
      visualKind: 'force-lab',
      controls: ['magnitude', 'area'],
      labOptions: { showSurfaceNormal: true, showArea: true, showDecomposition: false, allowSurfaceSelection: true },
      presetId: 'uniaxial-compression',
      magnitude: 0,
      vectors: false,
      outline: false,
      grid: false,
      spotlight: 'traction',
      prompt: 'What is |t̄| for 5 kN distributed uniformly over 100 cm²?',
      choices: [
        { id: 'point-zero-five', label: '0.05 MPa', correct: false, feedback: 'Check the conversion from square centimeters to square meters.' },
        { id: 'point-five', label: '0.50 MPa', correct: true, feedback: 'Correct. 5,000 N / 0.01 m² = 500,000 Pa = 0.50 MPa.' },
        { id: 'five', label: '5.0 MPa', correct: false, feedback: 'That is one order of magnitude too large.' },
      ],
      responseOverride: 'Average traction carries both the direction of the resultant force and units of stress.',
    },
    {
      id: 'decompose-traction',
      label: 'Resolve normal and shear',
      title: 'Resolve traction into normal and shear components',
      activeLabel: 'Traction decomposition',
      activeNumber: 'F5',
      body: 'Project traction onto the outward surface normal. The signed projection is normal traction, tn; inward loading gives tn < 0. The remaining in-plane vector is shear traction, τ. Drag the force and watch both components change continuously.',
      task: 'Choose Oblique, then drag the handle until the normal and shear magnitudes are approximately equal.',
      visualKind: 'force-lab',
      controls: ['components', 'area', 'presets'],
      labOptions: { showSurfaceNormal: true, showArea: true, showDecomposition: true, allowSurfaceSelection: true },
      presetId: 'pure-shear',
      magnitude: 0,
      vectors: false,
      outline: false,
      grid: false,
      spotlight: 'decomposition',
      prompt: 'For a force at 45° to the surface normal, how do |σn| and |τ| compare?',
      choices: [
        { id: 'normal-larger', label: '|σn| is larger', correct: false, feedback: 'At 45°, the normal and tangential projections have equal magnitudes.' },
        { id: 'equal', label: 'They are equal', correct: true, feedback: 'Correct. The sine and cosine projections are equal at 45°.' },
        { id: 'shear-zero', label: '|τ| is zero', correct: false, feedback: 'Shear vanishes only when the force is exactly normal to the plane.' },
      ],
      responseOverride: 'Normal stress and shear traction are components of the same traction vector on a selected plane.',
    },
    {
      id: 'traction-to-tensor',
      label: 'Connect to the tensor',
      title: 'One tensor describes traction on every plane',
      activeLabel: 'Cauchy stress relation',
      activeNumber: 'S1',
      body: 'At a point, the stress tensor maps a plane normal to its traction vector. Because this application declares compression positive, the relation is t(n) = −σn. The matrix is an operator connecting all plane orientations to their tractions—not a list of unrelated arrows.',
      task: 'Orbit the cube and identify the single active normal component in the matrix.',
      visualKind: 'stress-state',
      presetId: 'uniaxial-compression',
      magnitude: 20,
      vectors: true,
      outline: true,
      grid: true,
      spotlight: 'tensor',
      responseOverride: 'A uniaxial state contains one normal tensor component and no shear components.',
    },
    {
      id: 'compare-uniaxial-loading',
      label: 'Compare tension and compression',
      title: 'Reverse loading and predict the response',
      activeLabel: 'Uniaxial tension',
      activeNumber: 'S2',
      body: 'The current convention takes compression as positive and tension as negative. The tensor describes loading; the block response remains a deliberately qualitative teaching model.',
      visualKind: 'stress-state',
      presetId: 'uniaxial-tension',
      magnitude: 28,
      vectors: true,
      outline: true,
      grid: true,
      spotlight: 'response',
      prompt: 'What change should be most visible along the loaded x-axis?',
      choices: [
        { id: 'shorten', label: 'It shortens', correct: false, feedback: 'Shortening is the expected qualitative response to compression along x.' },
        { id: 'extend', label: 'It extends', correct: true, feedback: 'Correct. The block extends parallel to the tensile loading.' },
        { id: 'unchanged', label: 'It is unchanged', correct: false, feedback: 'The applied tensile component produces visible extension in this qualitative model.' },
      ],
      responseOverride: 'Tension is negative in the selected convention and produces qualitative extension along the loaded axis.',
    },
    {
      id: 'construct-pure-shear',
      label: 'Examine pure shear',
      title: 'Shear changes shape without requiring volume change',
      activeLabel: 'Pure shear state',
      activeNumber: 'S3',
      body: 'Off-diagonal tensor components describe shear traction on coordinate planes. Compare the solid block with its undeformed outline and separate distortion from dilation.',
      visualKind: 'stress-state',
      presetId: 'pure-shear',
      magnitude: 28,
      vectors: true,
      outline: true,
      grid: true,
      spotlight: 'shear',
      prompt: 'What changes most in this qualitative pure-shear example?',
      choices: [
        { id: 'volume', label: 'Volume', correct: false, feedback: 'The modeled shear deformation is approximately volume preserving.' },
        { id: 'shape', label: 'Shape', correct: true, feedback: 'Correct. The block distorts while volume remains approximately unchanged.' },
        { id: 'nothing', label: 'Neither', correct: false, feedback: 'Compare the solid edges with the reference outline.' },
      ],
      responseOverride: 'The block distorts while its modeled volume remains approximately constant.',
    },
    {
      id: 'combine-stress-components',
      label: 'Combine components',
      title: 'Three-dimensional stress states combine components',
      activeLabel: 'Combined stress state',
      activeNumber: 'S4',
      body: 'Normal and shear components can act simultaneously. Read the matrix, identify which faces carry each traction, and distinguish the stated stress from the assumed material response.',
      task: 'Name one normal component and one shear component visible in the current tensor.',
      visualKind: 'stress-state',
      presetId: 'simple-shear-triaxial-compression',
      magnitude: 30,
      vectors: true,
      outline: true,
      grid: true,
      spotlight: 'combined',
      responseOverride: 'Combined components can change shape and volume at the same time in the qualitative response model.',
    },
    {
      id: 'open-stress-explorer',
      label: 'Open the stress laboratory',
      title: 'Continue in the open laboratory',
      activeLabel: 'Stress-state laboratory',
      activeNumber: 'S5',
      body: 'Use Explore mode to compare all ten states, change tensor components, and test explanations. This stress module is one part of the larger Structural Visualizer curriculum.',
      task: 'Choose two states with similar magnitudes and explain why their block responses differ.',
      visualKind: 'stress-state',
      presetId: 'biaxial-tension-compression',
      magnitude: 26,
      vectors: true,
      outline: true,
      grid: true,
      spotlight: 'explore',
      responseOverride: 'Continue into the stress laboratory and construct your own comparisons.',
      final: true,
    },
  ],
};

export function getLessonStep(index) {
  return STRESS_LESSON.steps[Math.min(Math.max(index, 0), STRESS_LESSON.steps.length - 1)];
}

export function isLessonChoiceCorrect(step, choiceId) {
  return step.choices?.find((choice) => choice.id === choiceId)?.correct ?? false;
}
